# Generated by Django 6.0.7 on 2026-07-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='theRentOS asset ID, used to avoid duplicates on re-sync', max_length=50, unique=True)),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('odometer', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('location_base', models.CharField(blank=True, max_length=100)),
                ('location_current', models.CharField(blank=True, max_length=100)),
                ('vehicle_type', models.CharField(blank=True, max_length=50)),
                ('booking_type', models.CharField(blank=True, max_length=50)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('min_hours_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fastag_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_added', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
