# Generated by Django 6.0.7 on 2026-09-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_add_plate_number_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
