# Generated by Django 6.0.7 on 2026-09-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_vehicle_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
