# Generated by Django 6.0.7 on 2026-09-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_vehicle_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
