# Generated by Django 6.0.7 on 2026-10-09 15:27

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0006_vehicle_is_active_alter_vehicle_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=booking.models.booking_reference, editable=False, max_length=20, unique=True)),
                ('vehicle_plate_number', models.CharField(max_length=20)),
                ('cart_vehicle', models.JSONField(default=dict)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('pickup_location_id', models.PositiveIntegerField()),
                ('dropoff_location_id', models.PositiveIntegerField()),
                ('pickup_custom_payload', models.CharField(blank=True, max_length=500)),
                ('dropoff_custom_payload', models.CharField(blank=True, max_length=500)),
                ('rental_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_amount', models.DecimalField(decimal_places=2, default=1200, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=12)),
                ('assigned_email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'start_datetime', 'end_datetime'], name='booking_boo_vehicle_c6e992_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='booking_positive_duration')],
            },
        ),
    ]
