# Generated by Django 6.0.7 on 2026-09-28 18:13

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0006_vehicle_is_active_alter_vehicle_photo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(default=booking.models.generate_booking_reference, editable=False, max_length=20, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('vehicle_plate_number', models.CharField(blank=True, db_index=True, max_length=30)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('pickup_location_id', models.PositiveIntegerField()),
                ('dropoff_location_id', models.PositiveIntegerField()),
                ('pickup_custom_payload', models.CharField(blank=True, max_length=255)),
                ('dropoff_custom_payload', models.CharField(blank=True, max_length=255)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('therentos_estimate_id', models.CharField(blank=True, max_length=64)),
                ('therentos_synced', models.BooleanField(default=False)),
                ('cart_vehicle', models.JSONField(blank=True, default=dict)),
                ('therentos_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle_plate_number', 'start_datetime', 'end_datetime'], name='booking_boo_vehicle_ae5a99_idx')],
            },
        ),
    ]
