# Generated by Django 6.0.7 on 2026-10-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerecord',
            name='car',
        ),
        migrations.RemoveField(
            model_name='servicerecord',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='MaintenanceSchedule',
        ),
        migrations.DeleteModel(
            name='ServiceRecord',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
